name: Recorded Light
favicon: null
layout_spectrum: 0.6031554632354528
typography_spectrum: 0.9781064963899553
title: Recorded Light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.37451584031805396
  lightness: 0.7153906608000398
  saturation: 0.36491163191385567
  rhythmicContrast: 0.3200439775828272
purpose: []
