name: Recorded Light
favicon: null
layout_spectrum: 0.96332
typography_spectrum: 0.9781064963899553
title: Recorded Light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#002541'
    - '#00639a'
    - '#453c2a'
    - '#fdfefc'
  brandStrength: 0.37451584031805396
  lightness: 0.7153906608000398
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
