name: Recorded Light
favicon: null
layout_spectrum: 0.24742
typography_spectrum: 0.4474
title: Recorded Light
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#002541'
    - '#00639a'
    - '#453c2a'
    - '#fdfefc'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
